name: focus_mate
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  duration_picker: ^1.2.0
  equatable: ^2.0.5
  fl_chart: ^0.69.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.3
  flutter_riverpod: ^2.6.0
  freezed_annotation: ^2.4.1
  go_router: ^14.3.0
  hive: ^2.2.3
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.9.0
  package_info_plus: ^8.1.0
  path_provider: ^2.1.4
  riverpod_annotation: ^2.6.0
  shared_preferences: ^2.3.2
  supercharged: ^2.1.1
  talker_flutter: ^4.4.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  go_router_builder: ^2.7.1
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  pigeon: ^22.5.0

flutter:
  uses-material-design: true

