// Autogenerated from Pigeon (v21.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}
private class PopOverAPIPigeonCodecReader: FlutterStandardReader {
}

private class PopOverAPIPigeonCodecWriter: FlutterStandardWriter {
}

private class PopOverAPIPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PopOverAPIPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PopOverAPIPigeonCodecWriter(data: data)
  }
}

class PopOverAPIPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PopOverAPIPigeonCodec(readerWriter: PopOverAPIPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PopOverAPI {
  func togglePopOver() throws -> Bool
  func toggleRunningTimer() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PopOverAPISetup {
  static var codec: FlutterStandardMessageCodec { PopOverAPIPigeonCodec.shared }
  /// Sets up an instance of `PopOverAPI` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PopOverAPI?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let togglePopOverChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.focus_mate.PopOverAPI.togglePopOver\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      togglePopOverChannel.setMessageHandler { _, reply in
        do {
          let result = try api.togglePopOver()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      togglePopOverChannel.setMessageHandler(nil)
    }
    let toggleRunningTimerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.focus_mate.PopOverAPI.toggleRunningTimer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      toggleRunningTimerChannel.setMessageHandler { _, reply in
        do {
          let result = try api.toggleRunningTimer()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      toggleRunningTimerChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol MenuBarActionsProtocol {
  func toggleRunningTimer(completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class MenuBarActions: MenuBarActionsProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PopOverAPIPigeonCodec {
    return PopOverAPIPigeonCodec.shared
  }
  func toggleRunningTimer(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.focus_mate.MenuBarActions.toggleRunningTimer\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
