// Autogenerated from Pigeon (v21.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}
private class PopOverAPIPigeonCodecReader: FlutterStandardReader {
}

private class PopOverAPIPigeonCodecWriter: FlutterStandardWriter {
}

private class PopOverAPIPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PopOverAPIPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PopOverAPIPigeonCodecWriter(data: data)
  }
}

class PopOverAPIPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PopOverAPIPigeonCodec(readerWriter: PopOverAPIPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PopOverAPI {
  func togglePopOver() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PopOverAPISetup {
  static var codec: FlutterStandardMessageCodec { PopOverAPIPigeonCodec.shared }
  /// Sets up an instance of `PopOverAPI` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PopOverAPI?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let togglePopOverChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.focus_mate.PopOverAPI.togglePopOver\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      togglePopOverChannel.setMessageHandler { _, reply in
        do {
          let result = try api.togglePopOver()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      togglePopOverChannel.setMessageHandler(nil)
    }
  }
}
